# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.TimeField(verbose_name=b'fecha')),
                ('Hstock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apertura', models.TimeField(null=True, verbose_name=b'Horario de apertura')),
                ('cierre', models.TimeField(null=True, verbose_name=b'Horario de cierre')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posx', models.FloatField()),
                ('posy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodosDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to=b'', verbose_name=b'Foto de producto')),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('categoria', models.ManyToManyField(to='app.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to=b'', verbose_name=b'Foto de perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('activo', models.BooleanField()),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Horario')),
                ('localizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Localizacion')),
                ('pago', models.ManyToManyField(to='app.MetodosDePago')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
        migrations.AddField(
            model_name='historial',
            name='ProductoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Producto'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='vendedorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
