# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.TimeField(verbose_name=b'fecha')),
                ('Hstock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to=b'', verbose_name=b'Foto de producto')),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=60)),
                ('pago', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to=b'', verbose_name=b'Foto de perfil')),
                ('horarioApertura', models.TimeField(null=True, verbose_name=b'Horario de apertura')),
                ('horarioCierre', models.TimeField(null=True, verbose_name=b'Horario de cierre')),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
        migrations.AddField(
            model_name='historial',
            name='ProductoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Producto'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='vendedorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
    ]
