# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALU_USERNAME', models.CharField(max_length=20)),
                ('ALU_PASSWORD', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAV_IDALUMNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HIS_FECHA', models.TimeField(verbose_name='fecha')),
                ('HIS_STOCK', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRO_NOMBRE', models.CharField(max_length=20)),
                ('PRO_DESCRIPCION', models.CharField(max_length=200)),
                ('PRO_FOTO', models.ImageField(upload_to='', verbose_name='Foto de producto')),
                ('PRO_PRECIO', models.IntegerField()),
                ('PRO_STOCK', models.IntegerField()),
                ('PRO_CATEGORIA', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VEN_USERNAME', models.CharField(max_length=60)),
                ('VEN_PASSWORD', models.CharField(max_length=60)),
                ('VEN_TIPO', models.CharField(max_length=60)),
                ('VEN_PAGO', models.CharField(max_length=60)),
                ('VEN_FOTO', models.ImageField(upload_to='', verbose_name='Foto de perfil')),
                ('VEN_HORARIOA', models.TimeField(verbose_name='Horario de apertura')),
                ('VEN_HORARIOC', models.TimeField(verbose_name='Horario de cierre')),
                ('VEN_ACTIVO', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='PRO_IDVENDEDOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
        migrations.AddField(
            model_name='historial',
            name='HIS_IDPRODUCTO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Producto'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='FAV_IDVENDEDOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
    ]
