# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.TimeField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='apertura',
            field=models.TimeField(null=True, verbose_name='Horario de apertura'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='cierre',
            field=models.TimeField(null=True, verbose_name='Horario de cierre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='', verbose_name='Foto de producto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(upload_to='', verbose_name='Foto de perfil'),
        ),
    ]
