# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170529_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='horario',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='hapertura',
            field=models.TimeField(null=True, verbose_name='Horario de apertura'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='hcierre',
            field=models.TimeField(null=True, verbose_name='Horario de cierre'),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
